patreon: JackieWaltRyan
ko_fi: JackieWaltRyan
liberapay: JackieWaltRyan
custom: ['https://www.paypal.com/donate/?hosted_button_id=G3HY3UDX694WQ', 'https://www.privat24.ua/send/g21va', 'https://boosty.to/jackiewaltryan', 'https://www.donationalerts.com/r/jackiewaltryan']
